### ISSUE TITLE
Cargo.toml not found

### ISSUE THREAD

**Issue by bigbabyboost** [sioodmy/dotfiles#73]
Well, i tried rebuild seitch but showing error /nix/store/xxxxcargo.toml no such file

**Comment by xusiai** [comment]
Quick workaround is to disable nh:

Remove `inputs.nh.packages.${pkgs.system}.default ` from [this](https://github.com/sioodmy/dotfiles/blob/de2fc63c654118be9443f8689a4811d1fad8531c/system/core/nix.nix#L18C20-L18C20) line and `set nh.enable.true `to false on [this](https://github.com/sioodmy/dotfiles/blob/de2fc63c654118be9443f8689a4811d1fad8531c/system/core/nix.nix#L23C1-L23C19) line. 

You may also need to remove/comment out [this](https://github.com/sioodmy/dotfiles/blob/de2fc63c654118be9443f8689a4811d1fad8531c/home/cli/default.nix#L3C1-L3C2) line for it to build from live iso. You can re-enable both nh and helix and run `nixos-rebuild` once you've finished the installation and rebooted.
