### ISSUE TITLE
Full disk encryption

### ISSUE THREAD

**Issue by Leandro-Dalla-Nora** [sioodmy/dotfiles#78]
Hi! How are you?

You use the LUKS for the full disk encryption, at the hosts/anthe/hardware-configuration.nix. Do you make this encrytion in the instalation or post-instalation?

**Comment by Leandro-Dalla-Nora** [comment]
If you post-install encrypted, how you defined a password?

**Comment by sioodmy** [comment]
I don't think its possible to encrypt drives after installation.
